name: Synopsys Security Testing

on:
  push:
    branches: [ master, main ]

  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Windows, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Black Duck Scan
        uses: synopsys-sig/synopsys-action@v1.8.0
        
        ### Configure DETECT environment variables
        env: 
          
          DETECT_PROJECT_NAME: ${{ github.event.repository.name }}          
          DETECT_PROJECT_VERSION_NAME: ${{ github.ref_name }}
          DETECT_CODE_LOCATION_NAME: ${{ github.event.repository.name }}-${{ github.ref_name }}
          DETECT_EXCLUDED_DETECTOR_TYPES: 'GIT'     
          DETECT_POLICY_CHECK_FAIL_ON_SEVERITIES: BLOCKER,CRITICAL,MAJOR,MINOR
          BLACKDUCK_TRUST_CERT: true
          #DETECT_BLACKDUCK_RAPID_COMPARE_MODE: BOM_COMPARE_STRICT
          #DETECT_EXCLUDED_DIRECTORIES:
          #DETECT_FORCE_SUCCESS: true
        with:
          blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}
          blackduck_scan_full: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #include_diagnostics: true

          
          blackduck_scan_failure_severities: "ALL"
          
          #Optional- To enable feedback from Black Duck security testing as pull request comment
          
          blackduck_automation_prcomment: true
          #Optional- To enable autoamtic fix pull request creation if vulnerabilities are reported
          #blackduck_automation_fixpr: true
          #Mandatory if blackduck_automation_fixpr or blackduck_automation_prcomment is set true
          github_token: ${{ secrets.GITHUB_TOKEN }}
